[package]
name = "ruby_traits"
version = "1.0.2"
rust-version = "1.6"
license = "Apache-2.0 OR MIT"
description = "Traits for key comparison and hash function n Ruby Hash class."
keywords = ["hashmap", "no_std"]
categories = ["data-structures", "no-std"]
