//! Green-thread scheduler.
//!
//! monoruby multiplexes Ruby `Thread`s cooperatively on the one OS
//! thread (M:1). Each green thread owns a dedicated machine stack and an
//! `Executor` (see value/rvalue/thread.rs); context switches reuse the
//! fiber machinery's `rsp_save` swap, with three dedicated stubs
//! (`thread_invoker` / `switch_to_scheduler` / `scheduler_resume` in
//! codegen/arch/*/invoker.rs) that never touch `parent_fiber`, so a
//! thread root keeps `parent_fiber == None` and `Fiber.yield` at a
//! thread root takes the pre-existing error paths unchanged.
//!
//! ## Topology
//!
//! The scheduler loop (`scheduler_run`) only ever runs in the *main*
//! thread's context, event-loop style:
//!
//! - When the **main thread** blocks (`sleep`, `join`, ...), it calls
//!   `scheduler_run` as an ordinary function on its own stack. The loop
//!   dispatches runnable green threads until main is runnable again,
//!   then returns.
//! - When a **green thread** blocks, it records how it must be woken,
//!   then switches to the scheduler context saved in the process-global
//!   `SCHED_RSP` slot — i.e. control returns *out of* the loop's pending
//!   dispatch call, and the loop picks the next runnable thread.
//! - A green thread body that terminates switches back the same way
//!   (the `thread_invoker` epilogue), and the loop finalizes it.
//!
//! Because the loop always saves its context into `SCHED_RSP` right
//! before transferring control (both stubs do this), the slot always
//! holds the correct scheduler context, and only one loop instance can
//! ever be live (green threads never call `scheduler_run`).
//!
//! ## Switching discipline
//!
//! - Context switches happen only at VM safepoints (inside builtins), so
//!   every suspended thread's frames are GC-complete.
//! - `SCHEDULER` is a `RefCell`: it is never borrowed across a context
//!   switch, and no Ruby allocation happens while it is borrowed (GC
//!   marking re-enters it).

use std::cell::RefCell;
use std::collections::VecDeque;
use std::time::{Duration, Instant};

use crate::alloc::GC;
use crate::value::rvalue::{InterruptTiming, PendingInterrupt, ThreadInner, ThreadState};
use crate::*;

thread_local! {
    pub(crate) static SCHEDULER: RefCell<Scheduler> = RefCell::new(Scheduler::new());
}

thread_local! {
    /// The scheduler loop's saved machine context. Written by the
    /// context switch stubs; read back when a green thread parks or
    /// terminates. One slot per OS thread: the interpreter (scheduler,
    /// allocator, JIT) is per-OS-thread, and each OS thread's `Codegen`
    /// bakes *its own* slot address into its stubs — exactly like the
    /// alloc_flag. A process-global slot would be corrupted when several
    /// interpreters run on different OS threads (the test harness).
    static SCHED_RSP: std::cell::Cell<u64> = const { std::cell::Cell::new(0) };
}

/// Absolute address of this OS thread's `SCHED_RSP` slot, baked into the
/// context switch stubs generated by this thread's `Codegen`.
pub(crate) fn sched_rsp_addr() -> u64 {
    SCHED_RSP.with(|c| c.as_ptr() as u64)
}

pub(crate) struct Scheduler {
    /// All live (non-terminated) thread objects, including main — a GC
    /// root. Dead threads are pruned at finalization (user references
    /// keep them alive from the frames that hold them).
    threads: Vec<Value>,
    /// Runnable green threads, FIFO. (The running thread and the main
    /// thread are not queued here.)
    ready: VecDeque<Value>,
    /// Parked-with-deadline threads: `(deadline, thread)`. `None` means
    /// "sleep until woken" (`sleep` without duration / `Thread.stop`).
    /// Kept unsorted (n is small); stale entries — threads woken through
    /// another path first — are skipped on expiry by re-checking state.
    sleepers: Vec<(Option<Instant>, Value)>,
    /// Threads parked on fd readiness: `(fd, poll events, thread)`.
    /// One thread may hold several entries (`IO.select`); all are
    /// removed when it is woken. Stale entries (thread no longer
    /// `IoWaiting`) are pruned before each poll.
    io_waiters: Vec<(i32, i16, Value)>,
    /// The thread currently executing. `None` until the main thread
    /// object is lazily created.
    current: Option<Value>,
    main: Option<Value>,
    /// The main thread's `Executor`, refreshed at every `scheduler_run`
    /// entry. Only dereferenced (for GC marking) while `in_scheduler` —
    /// i.e. exactly while green threads can be the GC trigger and main's
    /// frames would otherwise be unreachable.
    main_exec: Option<std::ptr::NonNull<Executor>>,
    in_scheduler: bool,
}

impl Scheduler {
    fn new() -> Self {
        Self {
            threads: vec![],
            ready: VecDeque::new(),
            sleepers: vec![],
            io_waiters: vec![],
            current: None,
            main: None,
            main_exec: None,
            in_scheduler: false,
        }
    }

    pub(crate) fn mark(&self, alloc: &mut crate::alloc::Allocator<RValue>) {
        for t in &self.threads {
            t.mark(alloc);
        }
        // `current`/`main` and queue members are subsets of `threads`
        // except during pruning, so mark them too for safety.
        if let Some(t) = self.current {
            t.mark(alloc);
        }
        if let Some(t) = self.main {
            t.mark(alloc);
        }
        for t in &self.ready {
            t.mark(alloc);
        }
        for (_, t) in &self.sleepers {
            t.mark(alloc);
        }
        for (_, _, t) in &self.io_waiters {
            t.mark(alloc);
        }
        if self.in_scheduler
            && let Some(main_exec) = self.main_exec
        {
            // SAFETY: refreshed at scheduler_run entry; the main
            // executor outlives the loop that set it.
            unsafe { main_exec.as_ref().mark(alloc) };
        }
    }
}

/// Reset all scheduler state. Called when a fresh interpreter starts
/// (`Executor::init`) so state from a previous interpreter on the same
/// OS thread (e.g. the test harness) cannot leak across.
pub(crate) fn reset() {
    SCHEDULER.with(|s| *s.borrow_mut() = Scheduler::new());
}

/// GC root hook (called from `Root::mark`).
pub(crate) fn mark(alloc: &mut crate::alloc::Allocator<RValue>) {
    SCHEDULER.with(|s| s.borrow().mark(alloc));
}

/// Forensics (`MONORUBY_GC_BREAK`): one-line dump of the scheduler state
/// as seen by the GC root scan.
pub(crate) fn dump_state_for_gc() -> String {
    SCHEDULER.with(|s| {
        let s = s.borrow();
        format!(
            "in_scheduler={} main_exec={:?} main_exec_parent_fiber={:?} current={:016x} main={:016x} threads={} ready={} sleepers={} io_waiters={}",
            s.in_scheduler,
            s.main_exec,
            // SAFETY: forensics-only read; main_exec is live while set.
            s.main_exec
                .map(|e| unsafe { e.as_ref().parent_fiber() }),
            s.current.map(|v| v.id()).unwrap_or(0),
            s.main.map(|v| v.id()).unwrap_or(0),
            s.threads.len(),
            s.ready.len(),
            s.sleepers.len(),
            s.io_waiters.len(),
        ) + &s
            .main
            .map(|m| {
                let inner = m.as_thread_inner();
                format!(
                    " main_state={:?} main_resume_exec={:?} main_resume_parent_fiber={:?}",
                    inner.state,
                    inner.resume_exec,
                    // SAFETY: forensics-only read; resume_exec is live
                    // while the thread is parked.
                    inner
                        .resume_exec
                        .map(|e| unsafe { e.as_ref().parent_fiber() }),
                )
            })
            .unwrap_or_default()
    })
}

/// The `Thread` object for the currently running thread, creating the
/// main thread object lazily on first use.
pub(crate) fn current_thread(vm: &mut Executor) -> Value {
    ensure_main(vm);
    SCHEDULER.with(|s| s.borrow().current.unwrap())
}

/// The main thread's `Thread` object.
pub(crate) fn main_thread(vm: &mut Executor) -> Value {
    ensure_main(vm);
    SCHEDULER.with(|s| s.borrow().main.unwrap())
}

/// All alive threads (`Thread.list`).
pub(crate) fn thread_list(vm: &mut Executor) -> Vec<Value> {
    ensure_main(vm);
    SCHEDULER.with(|s| s.borrow().threads.clone())
}

/// Whether any *other* live thread exists (i.e. whether blocking
/// operations must go through the scheduler instead of really blocking).
pub(crate) fn has_other_live_threads() -> bool {
    SCHEDULER.with(|s| {
        let s = s.borrow();
        let cur = s.current;
        s.threads
            .iter()
            .any(|t| Some(*t) != cur && !t.as_thread_inner().is_dead())
    })
}

fn ensure_main(vm: &mut Executor) {
    let need = SCHEDULER.with(|s| s.borrow().main.is_none());
    if need {
        // Allocate before borrowing (allocation can trigger GC, which
        // re-enters the scheduler to mark it).
        let main = Value::new_thread(THREAD_CLASS, ThreadInner::main());
        SCHEDULER.with(|s| {
            let mut s = s.borrow_mut();
            if s.main.is_none() {
                s.threads.push(main);
                s.main = Some(main);
                s.current = Some(main);
            }
        });
    }
    let _ = vm;
}

fn is_current_main() -> bool {
    SCHEDULER.with(|s| {
        let s = s.borrow();
        s.current.is_some() && s.current == s.main
    })
}

/// Register a freshly created thread object and queue it for execution.
pub(crate) fn spawn(vm: &mut Executor, thread: Value) {
    ensure_main(vm);
    SCHEDULER.with(|s| {
        let mut s = s.borrow_mut();
        s.threads.push(thread);
        s.ready.push_back(thread);
    });
}

/// Wake a thread parked in `sleep` (`Thread#wakeup` / `#run`). Returns
/// false if the thread is dead.
pub(crate) fn wakeup(thread: Value) -> bool {
    SCHEDULER.with(|s| {
        let mut s = s.borrow_mut();
        let mut t = thread;
        let inner = t.as_thread_inner_mut();
        match inner.state() {
            ThreadState::Dead => false,
            ThreadState::Sleeping => {
                inner.state = ThreadState::Runnable;
                if Some(thread) != s.main {
                    s.ready.push_back(thread);
                }
                true
            }
            // Runnable / Created / Joining: nothing to do (CRuby's
            // wakeup only interrupts sleep).
            _ => true,
        }
    })
}

/// `Kernel#sleep` / `Thread.stop` through the scheduler. `dur == None`
/// sleeps until `#wakeup`. Returns the elapsed time.
pub(crate) fn sleep(
    vm: &mut Executor,
    globals: &mut Globals,
    dur: Option<Duration>,
) -> Result<Duration> {
    ensure_main(vm);
    // A pending interrupt allowed at blocking points fires *instead of*
    // parking (also the case where it was queued while running).
    let cur0 = SCHEDULER.with(|s| s.borrow().current.unwrap());
    deliver_pending_now(globals, cur0, true)?;
    set_park_blocking(cur0, true);
    let start = Instant::now();
    // An enormous duration (e.g. sleep(2**62)) must not overflow Instant
    // arithmetic — treat it as "sleep until woken".
    let deadline = dur.and_then(|d| start.checked_add(d));
    if is_current_main() {
        SCHEDULER.with(|s| {
            let mut s = s.borrow_mut();
            let mut main = s.main.unwrap();
            main.as_thread_inner_mut().state = ThreadState::Sleeping;
            s.sleepers.push((deadline, main));
        });
        scheduler_run(vm, globals)?;
        take_main_pending(globals, true)?;
    } else {
        let cur = SCHEDULER.with(|s| {
            let mut s = s.borrow_mut();
            let mut cur = s.current.unwrap();
            cur.as_thread_inner_mut().state = ThreadState::Sleeping;
            s.sleepers.push((deadline, cur));
            cur
        });
        park_switch(vm, cur)?;
    }
    Ok(start.elapsed())
}

/// `Thread.pass`: give every currently runnable thread a chance to run.
pub(crate) fn pass(vm: &mut Executor, globals: &mut Globals) -> Result<()> {
    ensure_main(vm);
    // `Thread.pass` is a delivery point for `:immediate` interrupts but
    // NOT for `:on_blocking` ones (it is not a blocking call).
    let cur0 = SCHEDULER.with(|s| s.borrow().current.unwrap());
    deliver_pending_now(globals, cur0, false)?;
    set_park_blocking(cur0, false);
    if is_current_main() {
        // Dispatch the threads that are ready *now* (not the ones they
        // enqueue), then come back to main. Like `scheduler_run`, the
        // main thread's frames must stay GC-reachable while a green
        // thread is the one triggering a collection, so publish the main
        // executor for the duration.
        SCHEDULER.with(|s| {
            let mut s = s.borrow_mut();
            s.main_exec = Some(root_exec(vm));
            s.in_scheduler = true;
        });
        // Same fd-waiter promotion as `scheduler_loop`: a main thread
        // spinning in `Thread.pass while …` never reaches the scheduler's
        // idle branch, so fd-parked green threads would otherwise starve.
        let mut result = if prune_io_waiters() {
            poll_io_waiters(vm, globals, Some(Instant::now()))
        } else {
            Ok(())
        };
        if result.is_ok() {
            let n = SCHEDULER.with(|s| s.borrow().ready.len());
            for _ in 0..n {
                let t = SCHEDULER.with(|s| s.borrow_mut().ready.pop_front());
                match t {
                    Some(t) => {
                        if let Err(err) = dispatch(globals, t) {
                            result = Err(err);
                            break;
                        }
                    }
                    None => break,
                }
            }
        }
        SCHEDULER.with(|s| {
            let mut s = s.borrow_mut();
            s.in_scheduler = false;
            let main = s.main.unwrap();
            s.current = Some(main);
        });
        result?;
        take_main_pending(globals, false)
    } else {
        let cur = SCHEDULER.with(|s| {
            let mut s = s.borrow_mut();
            let cur = s.current.unwrap();
            // Stay runnable; go to the back of the queue.
            s.ready.push_back(cur);
            cur
        });
        park_switch(vm, cur)
    }
}

/// `Thread#join` (also backs `#value`): park until `target` terminates
/// or the timeout expires. Returns whether the target is dead.
pub(crate) fn join(
    vm: &mut Executor,
    globals: &mut Globals,
    target: Value,
    timeout: Option<Duration>,
) -> Result<bool> {
    ensure_main(vm);
    let cur = SCHEDULER.with(|s| s.borrow().current.unwrap());
    if target == cur {
        return Err(MonorubyErr::threaderr(
            &globals.store,
            "Target thread must not be current thread",
        ));
    }
    let deadline = timeout.map(|d| Instant::now() + d);
    loop {
        deliver_pending_now(globals, cur, true)?;
        set_park_blocking(cur, true);
        if target.as_thread_inner().is_dead() {
            return Ok(true);
        }
        if let Some(dl) = deadline
            && Instant::now() >= dl
        {
            return Ok(false);
        }
        if is_current_main() {
            SCHEDULER.with(|s| {
                let mut s = s.borrow_mut();
                let mut main = s.main.unwrap();
                main.as_thread_inner_mut().state = ThreadState::Joining;
                let mut target = target;
                target.as_thread_inner_mut().joiners.push(main);
                if deadline.is_some() {
                    s.sleepers.push((deadline, main));
                }
            });
            scheduler_run(vm, globals)?;
            take_main_pending(globals, true)?;
        } else {
            SCHEDULER.with(|s| {
                let mut s = s.borrow_mut();
                let mut cur = s.current.unwrap();
                cur.as_thread_inner_mut().state = ThreadState::Joining;
                let mut target = target;
                target.as_thread_inner_mut().joiners.push(cur);
                if deadline.is_some() {
                    s.sleepers.push((deadline, cur));
                }
            });
            park_switch(vm, cur)?;
        }
    }
}

/// The effective `handle_interrupt` timing for `thread`'s queued pending
/// interrupt. Kill is unmaskable. For a raise, the innermost mask entry
/// whose class covers the exception's class wins; default `Immediate`.
fn pending_timing(store: &Store, thread: Value) -> Option<InterruptTiming> {
    let inner = thread.as_thread_inner();
    let pending = inner.pending.as_ref()?;
    let exc_class = match pending {
        PendingInterrupt::Kill => return Some(InterruptTiming::Immediate),
        PendingInterrupt::Raise(err) => err.class_id(),
    };
    for frame in inner.masks.iter().rev() {
        for (mask_class, timing) in frame {
            let Some(mask_module) = mask_class.is_class_or_module() else {
                continue;
            };
            // Class-hierarchy match: the exception class or any of its
            // superclasses equals the mask class.
            let mut m = Some(store.get_module(exc_class));
            while let Some(cur) = m {
                if cur.id() == mask_module.id() {
                    return Some(*timing);
                }
                m = cur.superclass();
            }
        }
    }
    Some(InterruptTiming::Immediate)
}

/// Take `thread`'s pending interrupt and turn it into the error to raise.
fn take_pending_as_error(mut thread: Value) -> Option<MonorubyErr> {
    let inner = thread.as_thread_inner_mut();
    match inner.pending.take()? {
        PendingInterrupt::Kill => {
            inner.killed = true;
            Some(kill_unwind_error())
        }
        PendingInterrupt::Raise(err) => Some(err),
    }
}

/// Deliver the current thread's pending interrupt *now* if its mask
/// timing allows delivery in this context (`at_blocking`: a real
/// blocking operation vs `Thread.pass` / handle_interrupt boundaries).
/// Called at every park entry and at handle_interrupt entry/exit.
pub(crate) fn deliver_pending_now(
    globals: &mut Globals,
    thread: Value,
    at_blocking: bool,
) -> Result<()> {
    let allowed = match pending_timing(&globals.store, thread) {
        None => false,
        Some(InterruptTiming::Immediate) => true,
        Some(InterruptTiming::OnBlocking) => at_blocking,
        Some(InterruptTiming::Never) => false,
    };
    if allowed
        && let Some(err) = take_pending_as_error(thread)
    {
        // Killing the main thread terminates the process.
        let is_main = SCHEDULER.with(|s| s.borrow().main) == Some(thread);
        if is_main && thread.as_thread_inner().killed {
            let mut t = thread;
            t.as_thread_inner_mut().killed = false;
            return Err(MonorubyErr::new(MonorubyErrKind::SystemExit(0), "exit"));
        }
        return Err(err);
    }
    Ok(())
}

/// Whether `thread` has a queued pending interrupt (optionally filtered
/// by exception class) — `Thread.pending_interrupt?`.
pub(crate) fn pending_interrupt_p(store: &Store, thread: Value, filter: Option<Module>) -> bool {
    let inner = thread.as_thread_inner();
    let Some(pending) = inner.pending.as_ref() else {
        return false;
    };
    let Some(filter) = filter else { return true };
    let exc_class = match pending {
        PendingInterrupt::Kill => return true,
        PendingInterrupt::Raise(err) => err.class_id(),
    };
    let mut m = Some(store.get_module(exc_class));
    while let Some(cur) = m {
        if cur.id() == filter.id() {
            return true;
        }
        m = cur.superclass();
    }
    false
}

/// Record whether the thread's imminent park is a blocking operation
/// (vs `Thread.pass`) — consulted when a queued `:on_blocking` interrupt
/// is delivered at resume.
fn set_park_blocking(mut thread: Value, blocking: bool) {
    thread.as_thread_inner_mut().park_blocking = blocking;
}

/// Push / pop a `handle_interrupt` mask frame on the current thread.
pub(crate) fn push_interrupt_mask(vm: &mut Executor, mask: Vec<(Value, InterruptTiming)>) {
    let mut cur = current_thread(vm);
    cur.as_thread_inner_mut().masks.push(mask);
}

pub(crate) fn pop_interrupt_mask(vm: &mut Executor) {
    let mut cur = current_thread(vm);
    cur.as_thread_inner_mut().masks.pop();
}

/// Queue an asynchronous interrupt (`Thread#kill` / `#raise`) for
/// `target` and wake it if parked. An interrupt aimed at the *current*
/// thread is returned as `Err` for the caller to raise in place.
pub(crate) fn interrupt(
    vm: &mut Executor,
    globals: &mut Globals,
    mut target: Value,
    int: PendingInterrupt,
) -> Result<()> {
    ensure_main(vm);
    // The kill unwind tag is allocated *before* borrowing the scheduler
    // (allocation can trigger GC, which re-enters it for marking).
    let cur = SCHEDULER.with(|s| s.borrow().current.unwrap());
    if target == cur {
        // Self-targeted interrupts honor the current handle_interrupt
        // mask: only `:immediate` delivers in place, everything else is
        // queued for a later delivery point.
        target.as_thread_inner_mut().pending = Some(int);
        if pending_timing(&globals.store, target) == Some(InterruptTiming::Immediate) {
            return deliver_pending_now(globals, target, false);
        }
        return Ok(());
    }
    if target.as_thread_inner().is_dead() {
        // CRuby: killing a dead thread is a no-op; raising into one is
        // also accepted (the exception is simply lost).
        return Ok(());
    }
    target.as_thread_inner_mut().pending = Some(int);
    // Wake a parked target so delivery happens promptly — unless the
    // target's handle_interrupt mask defers it (`:never`); a parked
    // thread counts as blocking, so `:on_blocking` wakes too.
    let wake = pending_timing(&globals.store, target) != Some(InterruptTiming::Never);
    if wake {
        SCHEDULER.with(|s| {
            let mut s = s.borrow_mut();
            let inner = target.as_thread_inner_mut();
            if matches!(
                inner.state(),
                ThreadState::Sleeping | ThreadState::Joining | ThreadState::IoWaiting
            ) {
                inner.state = ThreadState::Runnable;
                if Some(target) != s.main {
                    s.ready.push_back(target);
                }
            }
        });
    }
    Ok(())
}

/// The unrescuable unwind used to deliver `Thread#kill`: a `Throw` whose
/// tag is a fresh object no `catch` can ever match, so it runs every
/// ensure clause on the way out but passes through every rescue — and is
/// recognized in `finalize` as a clean death.
fn kill_unwind_error() -> MonorubyErr {
    MonorubyErr::throw(Value::object(OBJECT_CLASS), Value::nil())
}

/// Deliver a pending interrupt queued for the *main* thread. Called
/// after the scheduler returns control to a main-thread park.
fn take_main_pending(globals: &mut Globals, at_blocking: bool) -> Result<()> {
    let main = SCHEDULER.with(|s| s.borrow().main.unwrap());
    // The handle_interrupt mask still applies at this delivery point.
    deliver_pending_now(globals, main, at_blocking)
}

/// Park the current thread until `fd` reports one of `events` (or the
/// deadline passes, or another thread wakes/interrupts it). The caller
/// re-checks readiness afterwards — spurious wakeups are fine.
pub(crate) fn wait_fd(
    vm: &mut Executor,
    globals: &mut Globals,
    fd: i32,
    events: i16,
    deadline: Option<Instant>,
) -> Result<()> {
    wait_fds(vm, globals, &[(fd, events)], deadline)
}

/// Multi-fd variant of [`wait_fd`] (backs `IO.select`).
pub(crate) fn wait_fds(
    vm: &mut Executor,
    globals: &mut Globals,
    fds: &[(i32, i16)],
    deadline: Option<Instant>,
) -> Result<()> {
    ensure_main(vm);
    let cur0 = SCHEDULER.with(|s| s.borrow().current.unwrap());
    deliver_pending_now(globals, cur0, true)?;
    set_park_blocking(cur0, true);
    if is_current_main() {
        SCHEDULER.with(|s| {
            let mut s = s.borrow_mut();
            let mut main = s.main.unwrap();
            main.as_thread_inner_mut().state = ThreadState::IoWaiting;
            for (fd, ev) in fds {
                s.io_waiters.push((*fd, *ev, main));
            }
            if deadline.is_some() {
                s.sleepers.push((deadline, main));
            }
        });
        let result = scheduler_run(vm, globals);
        unregister_io_waiter(SCHEDULER.with(|s| s.borrow().main.unwrap()));
        result?;
        take_main_pending(globals, true)
    } else {
        let cur = SCHEDULER.with(|s| {
            let mut s = s.borrow_mut();
            let mut cur = s.current.unwrap();
            cur.as_thread_inner_mut().state = ThreadState::IoWaiting;
            for (fd, ev) in fds {
                s.io_waiters.push((*fd, *ev, cur));
            }
            if deadline.is_some() {
                s.sleepers.push((deadline, cur));
            }
            cur
        });
        let result = park_switch(vm, cur);
        unregister_io_waiter(cur);
        result
    }
}

fn unregister_io_waiter(thread: Value) {
    SCHEDULER.with(|s| {
        s.borrow_mut().io_waiters.retain(|(_, _, t)| *t != thread);
    });
}

/// Park the current green thread: record the context to resume, then
/// switch to the scheduler. Returns when the scheduler resumes us.
fn park_switch(vm: &mut Executor, mut cur: Value) -> Result<()> {
    cur.as_thread_inner_mut().resume_exec = Some(std::ptr::NonNull::from(&mut *vm));
    let switch = CODEGEN.with(|c| c.borrow().switch_to_scheduler);
    match switch(vm as *mut _, Value::nil()) {
        Some(_) => Ok(()),
        // Reserved for asynchronous interrupt injection (Thread#raise /
        // #kill): a resume that sets an error instead of a value.
        None => Err(vm.take_error()),
    }
}

/// The thread-root executor of `vm`'s fiber-parent chain.
///
/// GC root marking must always start from the thread-root executor: a
/// fiber's frame chain is reached *from* the frame that holds the Fiber
/// object (the resumer), never the other way round — `Executor::mark`
/// walks only its own cfp chain and does not cross fiber boundaries.
/// `execute_gc` performs this same walk for the triggering executor;
/// capturing `main_exec` from a park that happened *inside* a fiber
/// (e.g. `sleep` in an Enumerator body) without the walk would publish
/// the fiber's executor instead, leaving every frame of the main
/// thread's root chain invisible to a green-thread-triggered GC — a
/// use-after-free of anything referenced only by those frames.
fn root_exec(vm: &mut Executor) -> std::ptr::NonNull<Executor> {
    let mut cur = std::ptr::NonNull::from(&mut *vm);
    // SAFETY: `parent_fiber` links point at live executors while the
    // child fiber is running (the resumer is suspended on its stack).
    while let Some(parent) = unsafe { cur.as_ref().parent_fiber() } {
        cur = parent;
    }
    cur
}

/// The scheduler loop. Only ever called in the main thread's context,
/// while the main thread is parked; returns when main is runnable again.
fn scheduler_run(vm: &mut Executor, globals: &mut Globals) -> Result<()> {
    SCHEDULER.with(|s| {
        let mut s = s.borrow_mut();
        s.main_exec = Some(root_exec(vm));
        s.in_scheduler = true;
    });
    let result = scheduler_loop(vm, globals);
    SCHEDULER.with(|s| {
        let mut s = s.borrow_mut();
        s.in_scheduler = false;
        let main = s.main.unwrap();
        s.current = Some(main);
    });
    result
}

fn scheduler_loop(vm: &mut Executor, globals: &mut Globals) -> Result<()> {
    loop {
        wake_due_sleepers();
        // Promote fd-parked threads whose fd is already ready *before*
        // picking the next runnable thread. Without this zero-timeout
        // check, fd waiters are only polled in the idle branch below —
        // and a busy thread that never blocks (e.g. `loop { Thread.pass }`)
        // keeps the ready queue non-empty forever, starving every fd
        // waiter (a live-lock: the busy thread spins, the fd waiter —
        // possibly main — never wakes even though its fd is long ready).
        if prune_io_waiters() {
            poll_io_waiters(vm, globals, Some(Instant::now()))?;
        }
        let (main_ready, next) = SCHEDULER.with(|s| {
            let mut s = s.borrow_mut();
            let main_ready =
                s.main.unwrap().as_thread_inner().state() == ThreadState::Runnable;
            let next = if main_ready { None } else { s.ready.pop_front() };
            (main_ready, next)
        });
        if main_ready {
            return Ok(());
        }
        if let Some(t) = next {
            dispatch(globals, t)?;
            continue;
        }
        // Nothing runnable: wait for fd readiness and/or the nearest
        // deadline. Only when no thread can ever become runnable again
        // (no sleeper, no fd waiter) is it a deadlock.
        let has_io = prune_io_waiters();
        match (has_io, nearest_deadline()) {
            (true, deadline) => poll_io_waiters(vm, globals, deadline)?,
            (false, Some(deadline)) => interruptible_sleep_until(vm, globals, deadline)?,
            (false, None) => {
                return Err(MonorubyErr::fatal(
                    "No live threads left. Deadlock?".to_string(),
                ));
            }
        }
    }
}

/// Drop io_waiter entries whose thread was woken (or died) through
/// another path; returns whether any fd waiter remains.
fn prune_io_waiters() -> bool {
    SCHEDULER.with(|s| {
        let mut s = s.borrow_mut();
        s.io_waiters
            .retain(|(_, _, t)| t.as_thread_inner().state() == ThreadState::IoWaiting);
        !s.io_waiters.is_empty()
    })
}

fn wake_due_sleepers() {
    let now = Instant::now();
    SCHEDULER.with(|s| {
        let mut s = s.borrow_mut();
        let mut due = vec![];
        s.sleepers.retain(|(deadline, t)| {
            let mut t = *t;
            let state = t.as_thread_inner().state();
            // Entries whose thread was already woken (or died) through
            // another path are stale — drop them.
            if !matches!(
                state,
                ThreadState::Sleeping | ThreadState::Joining | ThreadState::IoWaiting
            ) {
                return false;
            }
            match deadline {
                Some(dl) if *dl <= now => {
                    due.push(t);
                    false
                }
                _ => true,
            }
        });
        let main = s.main;
        for mut t in due {
            t.as_thread_inner_mut().state = ThreadState::Runnable;
            if Some(t) != main {
                s.ready.push_back(t);
            }
        }
    });
}

/// Block in poll(2) over every fd-parked thread's descriptor, waking the
/// threads whose fds became ready (or errored/hung up — the woken thread
/// re-attempts its operation and surfaces the real errno). A signal
/// (EINTR) runs the VM poll point and the wait resumes.
fn poll_io_waiters(
    vm: &mut Executor,
    globals: &mut Globals,
    deadline: Option<Instant>,
) -> Result<()> {
    let entries: Vec<(i32, i16, Value)> = SCHEDULER.with(|s| s.borrow().io_waiters.clone());
    let mut pfds: Vec<libc::pollfd> = entries
        .iter()
        .map(|(fd, ev, _)| libc::pollfd {
            fd: *fd,
            events: *ev,
            revents: 0,
        })
        .collect();
    let timeout_ms: i32 = match deadline {
        Some(dl) => dl
            .saturating_duration_since(Instant::now())
            .as_millis()
            .min(i32::MAX as u128) as i32,
        None => -1,
    };
    // SAFETY: pfds is a valid array of pollfd for the duration of the call.
    let ret = unsafe { libc::poll(pfds.as_mut_ptr(), pfds.len() as _, timeout_ms) };
    if ret < 0 {
        let err = std::io::Error::last_os_error();
        if err.raw_os_error() == Some(libc::EINTR) {
            if crate::executor::execute_gc(vm, globals).is_none() {
                return Err(vm.take_error());
            }
            return Ok(());
        }
        return Err(MonorubyErr::ioerr(format!("poll failed: {err}")));
    }
    if ret > 0 {
        SCHEDULER.with(|s| {
            let mut s = s.borrow_mut();
            let main = s.main;
            for (pfd, (_, _, t)) in pfds.iter().zip(entries.iter()) {
                let mut t = *t;
                if pfd.revents != 0 && t.as_thread_inner().state() == ThreadState::IoWaiting {
                    t.as_thread_inner_mut().state = ThreadState::Runnable;
                    if Some(t) != main {
                        s.ready.push_back(t);
                    }
                }
            }
        });
    }
    Ok(())
}

fn nearest_deadline() -> Option<Instant> {
    SCHEDULER.with(|s| {
        s.borrow()
            .sleepers
            .iter()
            .filter_map(|(dl, _)| *dl)
            .min()
    })
}

/// Sleep the whole process until `deadline`, staying signal-responsive:
/// an EINTR runs the VM poll point (converting pending signals / running
/// trap handlers) and the sleep resumes for the remainder.
fn interruptible_sleep_until(
    vm: &mut Executor,
    globals: &mut Globals,
    deadline: Instant,
) -> Result<()> {
    loop {
        if crate::codegen::signal_table::PENDING_SIGNALS.load(std::sync::atomic::Ordering::Relaxed)
            != 0
            && crate::executor::execute_gc(vm, globals).is_none()
        {
            return Err(vm.take_error());
        }
        let now = Instant::now();
        if now >= deadline {
            return Ok(());
        }
        let remaining = deadline - now;
        let ts = libc::timespec {
            tv_sec: remaining.as_secs() as libc::time_t,
            tv_nsec: remaining.subsec_nanos() as libc::c_long,
        };
        // SAFETY: plain POSIX nanosleep on a valid timespec.
        let r = unsafe { libc::nanosleep(&ts, std::ptr::null_mut()) };
        if r == 0 {
            return Ok(());
        }
        if std::io::Error::last_os_error().raw_os_error() != Some(libc::EINTR) {
            return Ok(());
        }
        if crate::executor::execute_gc(vm, globals).is_none() {
            return Err(vm.take_error());
        }
    }
}

/// Run one green thread until it parks or terminates.
fn dispatch(globals: &mut Globals, mut thread: Value) -> Result<()> {
    enum Entry {
        Invoke(ProcData, *const Value, usize, *mut Executor),
        Resume(*mut Executor),
        /// Resume delivering a pending interrupt: the error is already
        /// set on the executor; resuming with 0 makes the parked
        /// `park_switch` return `Err(vm.take_error())`.
        ResumeInterrupt(*mut Executor),
        /// A never-started thread was killed / raised into: no body run.
        Skip(Option<MonorubyErr>),
    }
    // The kill tag allocates; do it outside the scheduler borrow.
    let kill_err = kill_unwind_error();
    // Whether the queued interrupt (if any) may be delivered at this
    // resume, per the target's handle_interrupt mask. The park kind
    // (blocking vs Thread.pass) was recorded at park time.
    let deliverable = match pending_timing(&globals.store, thread) {
        None => false,
        Some(InterruptTiming::Immediate) => true,
        Some(InterruptTiming::OnBlocking) => thread.as_thread_inner().park_blocking,
        Some(InterruptTiming::Never) => false,
    };
    let entry = SCHEDULER.with(|s| {
        let mut s = s.borrow_mut();
        s.current = Some(thread);
        let inner = thread.as_thread_inner_mut();
        if inner.state() == ThreadState::Created {
            let pending = inner.pending.take();
            match pending {
                Some(PendingInterrupt::Kill) => return Entry::Skip(None),
                Some(PendingInterrupt::Raise(err)) => return Entry::Skip(Some(err)),
                None => {}
            }
            inner.state = ThreadState::Runnable;
            inner.initialize_stack();
            let proc_data = ProcData::from_proc(inner.proc().unwrap());
            let args = inner.args();
            let (ptr, len) = (args.as_ptr(), args.len());
            Entry::Invoke(proc_data, ptr, len, inner.handle() as *mut Executor)
        } else {
            inner.state = ThreadState::Runnable;
            let exec = inner.resume_exec.take().unwrap().as_ptr();
            if !deliverable {
                // A masked pending interrupt stays queued; resume the
                // thread normally (it re-parks or delivers later at an
                // allowed point).
                return Entry::Resume(exec);
            }
            match inner.pending.take() {
                None => Entry::Resume(exec),
                Some(int) => {
                    let err = match int {
                        PendingInterrupt::Kill => {
                            inner.killed = true;
                            kill_err
                        }
                        PendingInterrupt::Raise(err) => err,
                    };
                    // SAFETY: `exec` is the parked context inside this
                    // thread's rooted RValue; setting its pending error
                    // is what the 0-resume below hands to park_switch.
                    unsafe { (*exec).set_error(err) };
                    Entry::ResumeInterrupt(exec)
                }
            }
        }
    });
    // The switch itself happens with no scheduler borrow held.
    let ret = match entry {
        Entry::Invoke(proc_data, args, len, handle) => {
            let invoker = CODEGEN.with(|c| c.borrow().thread_invoker);
            // SAFETY: `handle`/`args` point into the THREAD RValue,
            // which is rooted by the scheduler registry for the whole
            // run; the RValue arena does not move objects.
            invoker(
                unsafe { &mut *handle },
                globals,
                &proc_data,
                Value::nil(),
                args,
                len,
            )
        }
        Entry::Resume(exec) => {
            let resume = CODEGEN.with(|c| c.borrow().scheduler_resume);
            resume(exec, Value::nil().id())
        }
        Entry::ResumeInterrupt(exec) => {
            let resume = CODEGEN.with(|c| c.borrow().scheduler_resume);
            resume(exec, 0)
        }
        Entry::Skip(err) => {
            finalize_unstarted(globals, thread, err);
            SCHEDULER.with(|s| {
                let mut s = s.borrow_mut();
                s.current = s.main;
            });
            return Ok(());
        }
    };
    // Control is back in the scheduler context.
    if thread.as_thread_inner().body_terminated() {
        finalize(globals, thread, ret);
    }
    SCHEDULER.with(|s| {
        let mut s = s.borrow_mut();
        s.current = s.main;
    });
    Ok(())
}

/// A thread killed or raised-into before its body ever ran: mark it
/// dead without running the body (CRuby semantics for an unstarted
/// target), record the raise as its terminating exception, wake joiners.
fn finalize_unstarted(globals: &mut Globals, mut thread: Value, err: Option<MonorubyErr>) {
    {
        let inner = thread.as_thread_inner_mut();
        inner.killed = err.is_none();
        inner.exception = err;
        inner.result = None;
    }
    finalize_common(globals, thread);
}

/// A green thread's body finished: record the outcome, wake joiners,
/// prune the registry.
fn finalize(globals: &mut Globals, mut thread: Value, ret: Option<Value>) {
    {
        let inner = thread.as_thread_inner_mut();
        match ret {
            Some(v) => inner.result = Some(v),
            None => {
                let err = inner.take_error();
                if inner.killed && matches!(err.kind(), MonorubyErrKind::Throw(..)) {
                    // The kill unwind arrived at the thread root: a clean
                    // death (status false, join returns, nothing re-raised).
                    inner.result = None;
                } else {
                    // A bare `return` / `break` escaping a thread body has
                    // no enclosing frame on the thread's own stack:
                    // LocalJumpError (CRuby).
                    let err = match err.kind() {
                        MonorubyErrKind::MethodReturn(..) => {
                            MonorubyErr::localjumperr("unexpected return")
                        }
                        MonorubyErrKind::BlockBreak(..) => {
                            MonorubyErr::localjumperr("break from proc-closure")
                        }
                        _ => err,
                    };
                    inner.exception = Some(err);
                }
            }
        }
    }
    finalize_common(globals, thread);
}

/// Shared tail of thread termination: mark dead, wake joiners, prune the
/// registry, and report an unhandled exception per report_on_exception.
fn finalize_common(globals: &mut Globals, mut thread: Value) {
    SCHEDULER.with(|s| {
        let mut s = s.borrow_mut();
        let inner = thread.as_thread_inner_mut();
        inner.state = ThreadState::Dead;
        let joiners = std::mem::take(&mut inner.joiners);
        let main = s.main;
        for mut j in joiners {
            let ji = j.as_thread_inner_mut();
            if ji.state() == ThreadState::Joining {
                ji.state = ThreadState::Runnable;
                if Some(j) != main {
                    s.ready.push_back(j);
                }
            }
        }
        s.threads.retain(|t| *t != thread);
    });
    // A `SystemExit` that escapes any thread terminates the process: CRuby
    // re-raises it in the main thread (`Kernel#exit` from a thread exits
    // the interpreter once main handles it). The same forwarding applies
    // to *any* terminating exception when the thread — or the `Thread`
    // global default — has `abort_on_exception` set. The exception stays
    // recorded on the dead thread too (`#join` / `#value` re-raise it).
    forward_exception_to_main(globals, thread);
    // `Thread#report_on_exception` (default true): surface a terminating
    // exception on stderr (CRuby prints it when the thread dies). An
    // explicit `t.report_on_exception = false` (ivar set by the Ruby-side
    // accessor) suppresses it; a kill never reports, and neither does a
    // `SystemExit` (CRuby reports an abort_on_exception forwarding, but
    // never a SystemExit — that is the process exiting, not a crash).
    if thread
        .as_thread_inner()
        .exception
        .as_ref()
        .is_some_and(|err| matches!(err.kind(), MonorubyErrKind::SystemExit(_)))
    {
        return;
    }
    let report = globals
        .store
        .get_ivar(thread, IdentId::get_id("@report_on_exception"))
        .map(|v| v.as_bool())
        .unwrap_or(true);
    if !report {
        return;
    }
    let msg = {
        let inner = thread.as_thread_inner();
        inner
            .exception
            .as_ref()
            .map(|err| format!("{} ({})", err.message(), err.class_name(&globals.store)))
    };
    if let Some(msg) = msg {
        eprintln!("warning: thread terminated with exception (report_on_exception is true):");
        eprintln!("{msg}");
    }
}

/// Queue a dead thread's terminating exception as a pending interrupt on
/// the main thread (waking it if parked) when CRuby semantics call for
/// it: always for `SystemExit`, and for any exception when the thread or
/// the `Thread` global default has `abort_on_exception` set.
fn forward_exception_to_main(globals: &mut Globals, thread: Value) -> bool {
    let Some(err) = ({
        let inner = thread.as_thread_inner();
        inner.exception.clone()
    }) else {
        return false;
    };
    let forward = matches!(err.kind(), MonorubyErrKind::SystemExit(_)) || {
        let ivar = IdentId::get_id("@abort_on_exception");
        let per_thread = globals
            .store
            .get_ivar(thread, ivar)
            .map(|v| v.as_bool())
            .unwrap_or(false);
        let global_default = globals
            .store
            .get_ivar(globals.store.get_module(THREAD_CLASS).as_val(), ivar)
            .map(|v| v.as_bool())
            .unwrap_or(false);
        per_thread || global_default
    };
    if !forward {
        return false;
    }
    let Some(mut main) = SCHEDULER.with(|s| s.borrow().main) else {
        return false;
    };
    if main == thread {
        return false;
    }
    main.as_thread_inner_mut().pending = Some(PendingInterrupt::Raise(err));
    // Wake a parked main so delivery happens promptly (mirrors
    // `interrupt`); delivery itself still honors handle_interrupt masks.
    let inner = main.as_thread_inner_mut();
    if matches!(
        inner.state(),
        ThreadState::Sleeping | ThreadState::Joining | ThreadState::IoWaiting
    ) {
        inner.state = ThreadState::Runnable;
    }
    true
}
