def t(label)
  r = yield
  puts "#{label}\t#{r.inspect}"
rescue Exception => e
  # A NameError for a UTF-16LE method name cannot even spell its
  # message (CRuby raises CompatibilityError building it).
  msg = (e.message rescue "(no message: #{$!.class})")
  puts "#{label}\t#{e.class}: #{msg.lines.first.to_s.chomp}"
end
E = "EUC-JP"; j = "\u3042"; je = j.encode(E); u16 = "a".encode("UTF-16LE")
CASES = { "names" => -> { [Encoding::UTF_8.names, Encoding::BINARY.names, Encoding::EUC_JP.names, Encoding::Shift_JIS.names] },
  "dummy?" => -> { [Encoding::UTF_8.dummy?, Encoding::UTF_16.dummy?, Encoding::ISO_2022_JP.dummy?, Encoding::UTF_7.dummy?, Encoding::CP50220.dummy?] },
  "ascii_compatible?" => -> { [Encoding::UTF_8.ascii_compatible?, Encoding::UTF_16LE.ascii_compatible?, Encoding::ISO_2022_JP.ascii_compatible?] },
  "inspect/to_s/name" => -> { [Encoding::UTF_8.inspect, Encoding::BINARY.inspect, Encoding::UTF_16.inspect, Encoding::ISO_2022_JP.inspect, Encoding::UTF_8.to_s, Encoding::UTF_8.name, Encoding::UTF_8.name.frozen?, Encoding::UTF_8.name.encoding] },
  "identity" => -> { [Encoding::UTF_8 == Encoding.find("utf-8"), Encoding::UTF_8.equal?(Encoding.find("UTF-8")), Encoding::UTF_8.eql?(Encoding.find("UTF-8")), Encoding::UTF_8.hash == Encoding.find("UTF-8").hash] },
  "find specials" => -> { [Encoding.find("locale").to_s, Encoding.find("external").to_s, Encoding.find("filesystem").to_s] },
  "find internal" => -> { Encoding.find("internal") },
  "find nope" => -> { Encoding.find("nope") },
  "find symbol" => -> { Encoding.find(:utf_8) },
  "find enc obj" => -> { Encoding.find(Encoding::UTF_8).to_s },
  "find nil" => -> { Encoding.find(nil) },
  "find int" => -> { Encoding.find(1) },
  "find to_str" => -> { o = Object.new; def o.to_str = "EUC-JP"; Encoding.find(o).to_s },
  "find case" => -> { [Encoding.find("utf-8").to_s, Encoding.find("Utf-8").to_s, Encoding.find("EUCJP").to_s, Encoding.find("eucjp").to_s, Encoding.find("sjis").to_s, Encoding.find("binary").to_s, Encoding.find("ascii").to_s, Encoding.find("ASCII-8BIT").to_s, Encoding.find("cp932").to_s, Encoding.find("UTF8-MAC").to_s, Encoding.find("utf8-mac").to_s, Encoding.find("UTF-8-MAC").to_s, Encoding.find("UTF-8-HFS").to_s, Encoding.find("CP65001").to_s, Encoding.find("646").to_s, Encoding.find("ANSI_X3.4-1968").to_s, Encoding.find("CP1252").to_s, Encoding.find("ISO8859-1").to_s, Encoding.find("ISO-8859-1").to_s, Encoding.find("latin1") ] },
  "find with null" => -> { Encoding.find("UTF-8\0") },
  "sizes" => -> { [Encoding.list.size, Encoding.name_list.size, Encoding.aliases.size] },
  "aliases" => -> { %w[BINARY CP932 SJIS eucJP ASCII ANSI_X3.4-1968 646 UCS-2BE UTF-8-MAC CP65001 locale external filesystem internal CP1252 ISO8859-1].map { |a| [a, Encoding.aliases[a]] } },
  "aliases frozen" => -> { [Encoding.aliases.frozen?, Encoding.aliases.first.map(&:frozen?), Encoding.name_list.frozen?, Encoding.name_list.first.frozen?, Encoding.list.frozen?] },
  "constants" => -> { [Encoding.constants.size, Encoding.constants.sort.first(8), Encoding.constants.grep(/^[a-z]/i).select { |c| c.to_s =~ /[a-z]/ }.first(5)] },
  "frozen/new/allocate" => -> { [Encoding::UTF_8.frozen?, (Encoding.new rescue $!.class), (Encoding.allocate rescue $!.class)] },
  "dup" => -> { Encoding::UTF_8.dup },
  "clone" => -> { Encoding::UTF_8.clone },
  "Marshal round-trip" => -> { [Marshal.load(Marshal.dump(Encoding::UTF_8)).equal?(Encoding::UTF_8), Marshal.dump(Encoding::EUC_JP).bytes] },
  "replicate" => -> { Encoding::UTF_8.replicate("X") },
  "<=>" => -> { Encoding::UTF_8 <=> Encoding::UTF_8 },
  "default_external=" => -> { [Encoding.default_external.to_s, Encoding.default_internal, (Encoding.default_external = "EUC-JP"; r = Encoding.default_external.to_s; Encoding.default_external = "US-ASCII"; r), (Encoding.default_external = nil rescue $!.message), (Encoding.default_external = "nope" rescue $!.message), (Encoding.default_external = Encoding::UTF_16 rescue $!.message), Encoding.default_external.to_s] },
  "default_internal=" => -> { [(Encoding.default_internal = "EUC-JP"; r = Encoding.default_internal.to_s; Encoding.default_internal = nil; r), (Encoding.default_internal = "nope" rescue $!.message), Encoding.default_internal, (Encoding.default_internal = Encoding::ISO_2022_JP rescue $!.message), (Encoding.default_internal = nil), Encoding.default_internal] },
  "locale_charmap" => -> { Encoding.locale_charmap },
  "Encoding.compatible? enc objs" => -> { [Encoding.compatible?(Encoding::US_ASCII, Encoding::BINARY)&.to_s, Encoding.compatible?(Encoding::BINARY, Encoding::US_ASCII)&.to_s, Encoding.compatible?(Encoding::UTF_8, Encoding::US_ASCII)&.to_s, Encoding.compatible?(Encoding::US_ASCII, Encoding::UTF_8)&.to_s, Encoding.compatible?(Encoding::UTF_8, Encoding::BINARY)&.to_s, Encoding.compatible?(Encoding::EUC_JP, Encoding::US_ASCII)&.to_s, Encoding.compatible?(Encoding::EUC_JP, Encoding::Shift_JIS)&.to_s, Encoding.compatible?(Encoding::UTF_16LE, Encoding::US_ASCII)&.to_s, Encoding.compatible?(Encoding::ISO_2022_JP, Encoding::US_ASCII)&.to_s, Encoding.compatible?(Encoding::ISO_2022_JP, Encoding::ISO_2022_JP)&.to_s, Encoding.compatible?(Encoding::UTF_8, "abc")&.to_s, Encoding.compatible?("abc", Encoding::EUC_JP)&.to_s, Encoding.compatible?(j, Encoding::EUC_JP)&.to_s, Encoding.compatible?(Encoding::EUC_JP, j)&.to_s, Encoding.compatible?(Encoding::EUC_JP, "\xff".b)&.to_s, Encoding.compatible?(:abc, je)&.to_s, Encoding.compatible?(/a/, je)&.to_s, Encoding.compatible?(je, /a/)&.to_s, Encoding.compatible?(/#{j}/, je)&.to_s, Encoding.compatible?(1, "a")&.to_s, Encoding.compatible?("a", 1)&.to_s, Encoding.compatible?(nil, "a")&.to_s, Encoding.compatible?(Object.new, "a")&.to_s] },
  "join: empty sep" => -> { [[u16].join("").encoding, [u16, u16].join.encoding, [u16].join.bytes] },
  "join: sep given" => -> { [u16].join(",") },
  "join: euc sep" => -> { [[j].join("".encode(E)).encoding, [].join("x".encode(E)).encoding, ["a".encode(E)].join.encoding, ["a".encode(E), "b".encode("Shift_JIS")].join.encoding] },
  "join: mixed" => -> { [["a", je].join.encoding, ["a".b, "b"].join.encoding, [1, j].join.encoding, [].join.encoding, [[j], je].join.encoding, [j, [je]].join.encoding] },
  "join: incompat" => -> { [j, je].join },
  "join: bin+u8" => -> { ["\xff".b, j].join },
  "join: bin ascii + u8" => -> { ["abc".b, j].join.encoding },
  "join: u8 + bin high" => -> { [j, "\xff".b].join },
  "join: nested incompat" => -> { [[j], ["\xff".b]].join },
  "join: sep incompat" => -> { [j, "a"].join("\xff".b) },
  "join: sym" => -> { [:a, je.to_sym].join.encoding },
  "join: sym u8+euc" => -> { [j.to_sym, je.to_sym].join },
  "chr: basics" => -> { [65.chr.encoding, 200.chr.encoding, 255.chr.valid_encoding?, 0.chr.encoding, 65.chr("BINARY").encoding] },
  "chr: 256" => -> { 256.chr },
  "chr: 0x3042 utf8" => -> { 0x3042.chr(Encoding::UTF_8).encoding },
  "chr: 0x3042 no enc" => -> { 0x3042.chr },
  "chr: 0x3042 default_internal" => -> { Encoding.default_internal = "UTF-8"; r = 0x3042.chr.encoding; Encoding.default_internal = nil; r },
  "chr: euc cell" => -> { [0xA4A2.chr(E).bytes, 0xA4A2.chr(E).encoding, 0xA4A2.chr(E).ord] },
  "chr: euc 0x3042" => -> { 0x3042.chr(E) },
  "chr: sjis" => -> { [0x82A0.chr("Shift_JIS").bytes, 0x82A0.chr("Shift_JIS").ord, 0xB1.chr("Shift_JIS").ord] },
  "chr: euc kana" => -> { [0x8EB1.chr(E).bytes, 0x8EB1.chr(E).ord] },
  "chr: euc 0212" => -> { [0x8FA2AF.chr(E).bytes, 0x8FA2AF.chr(E).ord] },
  "chr: euc 0xff" => -> { 0xFF.chr(E) },
  "chr: euc 0x80" => -> { 0x80.chr(E) },
  "chr: euc 0xA4" => -> { 0xA4.chr(E) },
  "chr: usascii 0x80" => -> { 0x80.chr("US-ASCII") },
  "chr: latin1 0x80" => -> { 0x80.chr("ISO-8859-1").encoding },
  "chr: utf8 too big" => -> { 0x110000.chr("UTF-8") },
  "chr: utf8 surrogate" => -> { 0xD800.chr("UTF-8") },
  "chr: utf16" => -> { [0x3042.chr("UTF-16LE").bytes, 0x10000.chr("UTF-16LE").bytes, 0x3042.chr("UTF-32BE").bytes, 0x41.chr("UTF-16BE").bytes] },
  "chr: euckr" => -> { [0xC7D1.chr("EUC-KR").ord, 0xC7D1.chr("EUC-KR").bytes] },
  "chr: big5" => -> { [0xA4A4.chr("Big5").ord] },
  "chr: gbk" => -> { [0x8140.chr("GBK").ord] },
  "chr: gb18030 4byte" => -> { 0x81308130.chr("GB18030").ord },
  "chr: gb18030 2byte" => -> { 0xB0A1.chr("GB18030").ord },
  "chr: cp949" => -> { 0x8C63.chr("CP949").ord },
  "chr: iso2022" => -> { 0x3042.chr("ISO-2022-JP") },
  "chr: utf7" => -> { 0x41.chr("UTF-7") },
  "chr: negative" => -> { -1.chr },
  "chr: binary 0x3042" => -> { 0x3042.chr("BINARY") },
  "chr: bad enc name" => -> { 65.chr("NOPE") },
  "chr: enc obj" => -> { 65.chr(Encoding::EUC_JP).encoding },
  "chr: stateless" => -> { 0x92A4A2.chr("stateless-ISO-2022-JP").bytes },
  "chr: emacs-mule" => -> { 0x41.chr("Emacs-Mule").encoding },
  "chr: cesu-8" => -> { 0xC6.chr("CESU-8") },
  "chr: utf8-mac" => -> { 0xC3A9.chr("UTF8-MAC") },
  "conv identity" => -> { Encoding::Converter.new("UTF-8", "UTF-8") },
  "conv per dst (missing)" => -> { Encoding.list.reject(&:dummy?).map { |e| [e.to_s, (Encoding::Converter.new("UTF-8", e); "ok" rescue $!.class.to_s.split("::").last)] }.reject { |n, r| r == "ok" || n == "UTF-8" } },
  "conv per src (missing)" => -> { Encoding.list.reject(&:dummy?).map { |e| [e.to_s, (Encoding::Converter.new(e, "UTF-8"); "ok" rescue $!.class.to_s.split("::").last)] }.reject { |n, r| r == "ok" || n == "UTF-8" } },
  "conv dummies" => -> { Encoding.list.select(&:dummy?).map { |e| [e.to_s, (Encoding::Converter.new("UTF-8", e); "ok" rescue $!.class.to_s.split("::").last), (Encoding::Converter.new(e, "UTF-8"); "ok" rescue $!.class.to_s.split("::").last)] } },
  "convpath pairs" => -> { list = Encoding.list; pairs = []; list.each { |a| list.each { |b| pairs << [a.to_s, b.to_s] if (Encoding::Converter.search_convpath(a, b) rescue nil) } }; [pairs.size, pairs.map(&:first).uniq.size, pairs.map(&:last).uniq.size] },
  "convpath pairs by src" => -> { list = Encoding.list; list.map { |a| [a.to_s, list.count { |b| (Encoding::Converter.search_convpath(a, b) rescue nil) }] }.sort_by { |_, n| -n } },
  "ivar euc name" => -> { o = Object.new; o.instance_variable_set("@#{je}", 1); [o.instance_variables.map(&:encoding), o.instance_variable_get("@#{j}"), o.instance_variable_get("@#{je}")] },
  "ivar u8 name" => -> { o = Object.new; o.instance_variable_set("@#{j}", 1); [o.instance_variables, o.instance_variables.map(&:encoding), o.instance_variable_get("@#{je}")] },
  "ivar bin name" => -> { o = Object.new; o.instance_variable_set("@#{j}".b, 1); [o.instance_variables.map(&:encoding), o.instance_variable_get("@#{j}")] },
  "ivar bin bad" => -> { o = Object.new; o.instance_variable_set("@\xff".b, 1); o.instance_variables.map(&:inspect) },
  "cvar/const euc name" => -> { c = Class.new; c.class_variable_set("@@#{je}", 1); c.const_set("X#{je}", 2); [c.class_variables.map(&:encoding), c.constants.map(&:encoding), c.const_get("X#{j}"), c.class_variable_get("@@#{j}")] },
  "const_set bad enc" => -> { Object.const_set("X\xff".b, 1) },
  "method name euc" => -> { c = Class.new; c.define_method(je) { 3 }; [c.instance_methods(false).map(&:encoding), c.new.send(j), c.new.send(je), c.new.respond_to?(j), c.method_defined?(je), c.instance_method(j).name.encoding] },
  "send bin name" => -> { c = Class.new; c.define_method(j) { 3 }; c.new.send(j.b) },
  "send u16 name" => -> { c = Class.new; c.define_method(j) { 3 }; c.new.send(j.encode("UTF-16LE")) },
  "send bad bytes" => -> { Object.new.send("\xff".b) },
  "send empty" => -> { Object.new.send("") },
  "respond_to bad bytes" => -> { Object.new.respond_to?("\xff".b) },
  "define_method bad bytes" => -> { Class.new.define_method("\xff".b) { } },
  "alias euc" => -> { c = Class.new { def foo = 1 }; c.alias_method(je, :foo); c.new.send(j) },
  "Struct euc member" => -> { s = Struct.new(je.to_sym).new(9); [s.send(j), s.members.map(&:encoding), s.to_h.keys.map(&:encoding), s[j], s[je]] },
  "Hash kw euc" => -> { h = { je.to_sym => 1 }; [h[j.to_sym], h.keys.map(&:encoding), (->(**kw) { kw }).call(**h).keys] },
  "Symbol#to_proc bin" => -> { j.b.to_sym.to_proc.call(Struct.new(j.to_sym).new(5)) },
  "String#% euc fmt" => -> { [("%s".encode(E) % je).encoding, ("%s".encode(E) % "a").encoding, ("%s".encode(E) % j rescue $!.message), ("%s" % je).encoding, ("%d".encode(E) % 1).encoding, ("%c".encode(E) % 0xA4A2).bytes, ("%c".encode(E) % 0x3042 rescue $!.message), ("%c" % 0x3042).bytes, ("%c" % je).encoding, ("%c" % "ab").encoding, ("%c".b % 0xff).bytes, ("%c".b % 0x3042 rescue $!.message), ("%-4s|" % je), ("%-4s|" % j), ("%4s|" % "\u{1F363}"), ("%.1s|" % je), ("%.1s|" % "\u{1F363}a"), ("%s" % u16 rescue $!.message), ("%s".encode("UTF-16LE") % "a" rescue $!.message), (format("%s%s", je, "a").encoding), (format("%s%s", je, j) rescue $!.message), (format("%s", "\xff".b).encoding), (format("%s%s", "\xff".b, j) rescue $!.message), (format("%s", "abc".b).encoding), (format("%p", je).encoding), (format("%p", "\xff".b).encoding), (format("%s", je).encoding), (format("%s".encode(E), 1).encoding), (format("%5s|", "\xC7\xD1".force_encoding("EUC-KR"))), (format("%5s|", "a\x00b".force_encoding("UTF-16LE")) rescue $!.message), (format("%.2s|", "\xC7\xD1\xC7\xD1".force_encoding("EUC-KR")).bytes)] },
  "regex literal escapes" => -> { [/\xE3\x81\x82/.encoding, /\xE3\x81\x82/.fixed_encoding?, /\xE3\x81\x82/ =~ j, (/\xff/n.encoding), (Regexp.new("\xff".b).encoding), (/#{"\xff".b}/.encoding), (/#{je}/.encoding), (/#{je}/.fixed_encoding?), (/a#{je}/.encoding), (/#{j}#{je}/ rescue $!.class), (/#{"\xff".b}#{j}/ rescue $!.class), /\p{Hiragana}/.encoding, /\p{Hiragana}/.fixed_encoding?, /[あ]/.encoding, /\xC0/n.encoding, (/\u0080/ =~ "\x80".b rescue $!.message), (/a/ =~ "\x80".b), (/a/u =~ "\x80".b rescue $!.message), (/あ/ =~ "\x80".b rescue $!.message), (/\p{Alpha}/ =~ "\xC7\xD1".force_encoding("EUC-KR") rescue $!.message), (/./ =~ "\xC7\xD1".force_encoding("EUC-KR")), (/./n =~ "\xC7\xD1".force_encoding("EUC-KR")), (/\A.\z/ =~ "\xC7\xD1".force_encoding("EUC-KR")), (/\A.\z/ =~ je), (/\A.\z/ =~ j.encode("Shift_JIS")), (/\A.\z/ =~ j.encode("Big5")), (/\A.\z/ =~ j.encode("GBK")), (/\A.\z/ =~ j.encode("GB18030")), (/\A.\z/ =~ j.encode("CP949")), (/\A.\z/ =~ j.encode("EUC-TW")), (/\A.\z/ =~ j.encode("Emacs-Mule")), (/\A.\z/ =~ j.encode("stateless-ISO-2022-JP")), (/\A.\z/ =~ "\u00e9".encode("Windows-1252")), (/\A.\z/ =~ "\u00e9".encode("ISO-8859-1")), (/\A.\z/ =~ "\u0e01".encode("TIS-620")), (/\A.\z/ =~ "\u0416".encode("KOI8-R")), (/\A.\z/ =~ j.encode("UTF-16LE") rescue $!.message), (/\A.\z/ =~ j.encode("UTF8-MAC")), (/\A.\z/ =~ j.encode("CESU-8")), (/\A\w\z/ =~ je), (/\A\w\z/ =~ "\u00e9".encode("ISO-8859-1")), (/\A\w\z/ =~ "\u00e9".encode("Windows-1252")), (/\A\w\z/ =~ "\u00e9".encode("IBM437")), (/\A[[:alpha:]]\z/ =~ "\u00e9".encode("ISO-8859-1")), (/\A[[:alpha:]]\z/ =~ "\u00e9".encode("IBM437")), (/(?i)\Aé\z/.encode("ISO-8859-1") rescue $!.class), (Regexp.new("\\A\u00c9\\z".encode("ISO-8859-1"), Regexp::IGNORECASE) =~ "\u00e9".encode("ISO-8859-1")), (Regexp.new("\\A\u00c9\\z".encode("Windows-1252"), Regexp::IGNORECASE) =~ "\u00e9".encode("Windows-1252")), (Regexp.new("\\A\u0416\\z".encode("KOI8-R"), Regexp::IGNORECASE) =~ "\u0436".encode("KOI8-R")), (Regexp.new("\\Aあ\\z".encode(E), Regexp::IGNORECASE) =~ je), (/\Aあ\z/i =~ j), (/\AÉ\z/i =~ "é"), (/\Aß\z/i =~ "ss"), (/\Ass\z/i =~ "ß"), (/\Aσ\z/i =~ "ς"), (/\AK\z/i =~ "\u212A"), (/[[:alpha:]]/ =~ "\u3042"), (/\w/ =~ "\u3042"), (/\w/n =~ "\u3042".b), (/[[:alpha:]]/n =~ "\xE3".b), (/\d/ =~ "\u0663"), (/[[:digit:]]/ =~ "\u0663"), (/\s/ =~ "\u3000"), (/[[:space:]]/ =~ "\u3000"), (/\h/ =~ "\uFF21"), (/\R/ =~ "\u2028"), (/\X/ =~ "e\u0301").then { |m| $~[0].length }, (/\b/ =~ "\u3042a"), (/\p{Han}/ =~ "漢"), (/\p{Katakana}/ =~ "ア"), (/\p{Emoji}/ =~ "🍣"), (/\p{In_Hiragana}/ =~ "あ"),] },
}
# bin/encoding-matrix isolates a crash: `LIST=units` names the cases and
# `ONLY=<case>` runs one.
(puts CASES.keys; exit) if ENV["LIST"]
only = ENV["ONLY"]
CASES.each { |k, v| next if only && k != only; $stdout.flush; t(k, &v) }
