# String behaviour matrix: methods × encodings × inputs, CRuby vs monoruby.
def enc(s, e) = s.b.force_encoding(e)
INPUTS = {
  "u8:ascii"      => "Hello, World",
  "u8:latin"      => "héllo wörld",
  "u8:jp"         => "日本語テキスト",
  "u8:mixed"      => "abc日本xyz",
  "u8:bad"        => "ab\xFF\xFEcd".b.force_encoding("UTF-8"),
  "u8:trunc"      => "ab\xE3\x81".b.force_encoding("UTF-8"),
  "u8:empty"      => "",
  "u8:combining"  => "éà",
  "u8:astral"     => "🍣sushi🍺",
  "u8:crlf"       => "a\r\nb\nc\r",
  "bin:ascii"     => "Hello".b,
  "bin:high"      => "\xFF\xFE\x80ab".b,
  "usascii:ok"    => enc("abc", "US-ASCII"),
  "usascii:bad"   => enc("ab\x80c", "US-ASCII"),
  "eucjp:ok"      => "日本語abc".encode("EUC-JP"),
  "eucjp:kana"    => enc("\x8E\xB1\x8E\xB2ab", "EUC-JP"),
  "eucjp:0212"    => enc("\x8F\xA2\xAFab", "EUC-JP"),
  "eucjp:bad"     => enc("a\xA4b", "EUC-JP"),
  "sjis:ok"       => "日本語abc".encode("Shift_JIS"),
  "sjis:kana"     => enc("\xB1\xB2ab", "Shift_JIS"),
  "sjis:bad"      => enc("a\x82b\x80", "Shift_JIS"),
  "cp932:ok"      => "①㈱abc".encode("Windows-31J"),
  "u16le:ok"      => "ab日".encode("UTF-16LE"),
  "u16be:ok"      => "ab日".encode("UTF-16BE"),
  "u16le:odd"     => enc("a\x00b", "UTF-16LE"),
  "u32be:ok"      => "a日".encode("UTF-32BE"),
  "l1:ok"         => enc("caf\xE9", "ISO-8859-1"),
  "euckr:ok"      => "한국어abc".encode("EUC-KR"),
  "big5:ok"       => "中文abc".encode("Big5"),
  "gbk:ok"        => "中文abc".encode("GBK"),
  "gb18030:ok"    => "中文abc𝄞".encode("GB18030"),
  "cp949:ok"      => "똠abc".encode("CP949"),
  "iso2022:ok"    => "日本abc".encode("ISO-2022-JP"),
  "utf7:dummy"    => enc("abc", "UTF-7"),
  "u8mac:ok"      => "é".encode("UTF8-MAC"),
  "koi8:ok"       => enc("\xD0\xD2\xC9\xD7\xC5\xD4", "KOI8-R"),
  "w1252:ok"      => enc("\x80\x93caf\xE9", "Windows-1252"),
}
def show(v)
  case v
  when String then "#{v.inspect}/#{v.encoding}/#{v.valid_encoding?}/#{v.ascii_only?}/#{v.frozen?}"
  when Array then "[" + v.map { |x| show(x) }.join(", ") + "]"
  when Symbol then "#{v.inspect}/#{v.encoding}"
  when Enumerator then "enum:" + show(v.first(3))
  when Regexp then "#{v.inspect}/#{v.encoding}/#{v.fixed_encoding?}"
  when MatchData then "md:" + show(v.to_a)
  else v.inspect
  end
end
CASES = {
  "length"        => ->(s) { s.length },
  "bytesize"      => ->(s) { s.bytesize },
  "chars"         => ->(s) { s.chars },
  "bytes.size"    => ->(s) { s.bytes.size },
  "codepoints"    => ->(s) { s.codepoints },
  "grapheme"      => ->(s) { s.grapheme_clusters },
  "ord"           => ->(s) { s.ord },
  "reverse"       => ->(s) { s.reverse },
  "upcase"        => ->(s) { s.upcase },
  "downcase"      => ->(s) { s.downcase },
  "capitalize"    => ->(s) { s.capitalize },
  "swapcase"      => ->(s) { s.swapcase },
  "upcase(:ascii)"=> ->(s) { s.upcase(:ascii) },
  "downcase(:fold)"=> ->(s) { s.downcase(:fold) },
  "upcase(:turkic)"=> ->(s) { s.upcase(:turkic) },
  "strip"         => ->(s) { s.strip },
  "chomp"         => ->(s) { s.chomp },
  "chop"          => ->(s) { s.chop },
  "succ"          => ->(s) { s.succ },
  "inspect"       => ->(s) { s.inspect },
  "dump"          => ->(s) { s.dump },
  "dump.undump"   => ->(s) { s.dump.undump },
  "to_sym"        => ->(s) { s.to_sym },
  "to_sym.to_s"   => ->(s) { s.to_sym.to_s },
  "b"             => ->(s) { s.b },
  "scrub"         => ->(s) { s.scrub },
  "scrub(?)"      => ->(s) { s.scrub("?") },
  "scrub{}"       => ->(s) { s.scrub { |b| "<#{b.unpack1('H*')}>" } },
  "unicode_normalize" => ->(s) { s.unicode_normalize },
  "unicode_normalized?" => ->(s) { s.unicode_normalized? },
  "+ 'x'"         => ->(s) { s + "x" },
  "+ 'x'.b"       => ->(s) { s + "x".b },
  "+ '\\xff'.b"   => ->(s) { s + "\xFF".b },
  "+ 'あ'"        => ->(s) { s + "あ" },
  "+ eucjp"       => ->(s) { s + "あ".encode("EUC-JP") },
  "<< 'x'"        => ->(s) { s.dup << "x" },
  "<< 0x3042"     => ->(s) { s.dup << 0x3042 },
  "<< 0xff"       => ->(s) { s.dup << 0xFF },
  "<< 'あ'"       => ->(s) { s.dup << "あ" },
  "<< '\\xff'.b"  => ->(s) { s.dup << "\xFF".b },
  "* 2"           => ->(s) { s * 2 },
  "== dup"        => ->(s) { s == s.dup },
  "== b"          => ->(s) { s == s.b },
  "== utf8"       => ->(s) { s == s.dup.force_encoding("UTF-8") },
  "eql? b"        => ->(s) { s.eql?(s.b) },
  "hash == b.hash"=> ->(s) { s.hash == s.b.hash },
  "<=> b"         => ->(s) { s <=> s.b },
  "<=> 'b'"       => ->(s) { s <=> "b" },
  "casecmp"       => ->(s) { s.casecmp(s.upcase) },
  "casecmp?"      => ->(s) { s.casecmp?(s.upcase) },
  "=~ /./"        => ->(s) { s =~ /./ },
  "=~ /a/"        => ->(s) { s =~ /a/ },
  "=~ /あ/"       => ->(s) { s =~ /あ/ },
  "=~ /./n"       => ->(s) { s =~ /./n },
  "match(/(.)/)"  => ->(s) { s.match(/(.)/) },
  "scan(/./)"     => ->(s) { s.scan(/./) },
  "index('b')"    => ->(s) { s.index("b") },
  "index('b',1)"  => ->(s) { s.index("b", 1) },
  "rindex('b')"   => ->(s) { s.rindex("b") },
  "index(/b/)"    => ->(s) { s.index(/b/) },
  "byteindex('b')"=> ->(s) { s.byteindex("b") },
  "byterindex('b')"=> ->(s) { s.byterindex("b") },
  "[1]"           => ->(s) { s[1] },
  "[1,2]"         => ->(s) { s[1, 2] },
  "[1..]"         => ->(s) { s[1..] },
  "[-2..]"        => ->(s) { s[-2..] },
  "['b']"         => ->(s) { s["b"] },
  "[/./]"         => ->(s) { s[/./] },
  "byteslice(1,2)"=> ->(s) { s.byteslice(1, 2) },
  "bytesplice"    => ->(s) { x = s.dup; x.bytesplice(0, 1, "Z"); x },
  "getbyte(1)"    => ->(s) { s.getbyte(1) },
  "setbyte"       => ->(s) { x = s.dup; x.setbyte(0, 0x41); x },
  "slice!(0)"     => ->(s) { x = s.dup; [x.slice!(0), x] },
  "insert(1,'x')" => ->(s) { s.dup.insert(1, "x") },
  "insert(1,'あ')"=> ->(s) { s.dup.insert(1, "あ") },
  "include?('b')" => ->(s) { s.include?("b") },
  "include?('あ')"=> ->(s) { s.include?("あ") },
  "start_with?('a')"=> ->(s) { s.start_with?("a") },
  "start_with?(/a/)"=> ->(s) { s.start_with?(/a/) },
  "end_with?('c')"=> ->(s) { s.end_with?("c") },
  "delete('a')"   => ->(s) { s.delete("a") },
  "delete('あ')"  => ->(s) { s.delete("あ") },
  "count('a')"    => ->(s) { s.count("a") },
  "count('a-z')"  => ->(s) { s.count("a-z") },
  "squeeze"       => ->(s) { s.squeeze },
  "tr('a','x')"   => ->(s) { s.tr("a", "x") },
  "tr('a','あ')"  => ->(s) { s.tr("a", "あ") },
  "tr('a-z','A-Z')"=> ->(s) { s.tr("a-z", "A-Z") },
  "tr_s"          => ->(s) { s.tr_s("a", "x") },
  "delete_prefix" => ->(s) { s.delete_prefix("a") },
  "delete_suffix" => ->(s) { s.delete_suffix("c") },
  "center(12,'*')"=> ->(s) { s.center(12, "*") },
  "center(12,'あ')"=> ->(s) { s.center(12, "あ") },
  "ljust(12)"     => ->(s) { s.ljust(12) },
  "rjust(12,'ab')"=> ->(s) { s.rjust(12, "ab") },
  "sub(/./,'X')"  => ->(s) { s.sub(/./, "X") },
  "sub('a','あ')" => ->(s) { s.sub("a", "あ") },
  "gsub(/./,'X')" => ->(s) { s.gsub(/./, "X") },
  "gsub(/(.)/){}" => ->(s) { s.gsub(/(.)/) { $1 * 2 } },
  "gsub(/a/,{})"  => ->(s) { s.gsub(/a/, "a" => "A") },
  "split('')"     => ->(s) { s.split("") },
  "split"         => ->(s) { s.split },
  "split('b')"    => ->(s) { s.split("b") },
  "split(/b/)"    => ->(s) { s.split(/b/) },
  "partition('b')"=> ->(s) { s.partition("b") },
  "rpartition(/b/)"=> ->(s) { s.rpartition(/b/) },
  "lines"         => ->(s) { s.lines },
  "each_line(chomp)"=> ->(s) { s.each_line(chomp: true).to_a },
  "each_char.first(3)"=> ->(s) { s.each_char.first(3) },
  "each_byte.first(3)"=> ->(s) { s.each_byte.first(3) },
  "prepend('あ')" => ->(s) { s.dup.prepend("あ") },
  "replace"       => ->(s) { x = +"zz"; x.replace(s) },
  "force(UTF-8)"  => ->(s) { s.dup.force_encoding("UTF-8") },
  "force(BINARY)" => ->(s) { s.dup.force_encoding("BINARY") },
  "force(EUC-JP)" => ->(s) { s.dup.force_encoding("EUC-JP") },
  "encode(UTF-8)" => ->(s) { s.encode("UTF-8") },
  "encode(UTF-16LE)"=> ->(s) { s.encode("UTF-16LE") },
  "encode(EUC-JP)"=> ->(s) { s.encode("EUC-JP") },
  "encode(SJIS)"  => ->(s) { s.encode("Shift_JIS") },
  "encode(US-ASCII)"=> ->(s) { s.encode("US-ASCII") },
  "encode(US-ASCII,undef)"=> ->(s) { s.encode("US-ASCII", undef: :replace) },
  "encode(UTF-8,invalid)"=> ->(s) { s.encode("UTF-8", invalid: :replace) },
  "encode(UTF-8,inv,repl)"=> ->(s) { s.encode("UTF-8", invalid: :replace, replace: "?") },
  "encode(UTF-8,xml)"=> ->(s) { s.encode("UTF-8", xml: :text) },
  "encode(UTF-8,univ)"=> ->(s) { s.encode("UTF-8", universal_newline: true) },
  "encode(UTF-8,crlf)"=> ->(s) { s.encode("UTF-8", crlf_newline: true) },
  "encode(UTF-8,fallback)"=> ->(s) { s.encode("US-ASCII", fallback: ->(c) { "<#{c.ord}>" }) },
  "encode(same)"  => ->(s) { s.encode(s.encoding) },
  "encode()"      => ->(s) { s.encode },
  "encode(BINARY)"=> ->(s) { s.encode("BINARY") },
  "encode(ISO-2022-JP)"=> ->(s) { s.encode("ISO-2022-JP") },
  "encode(UTF-7)" => ->(s) { s.encode("UTF-7") },
  "encode!(UTF-8)"=> ->(s) { x = s.dup; x.encode!("UTF-8"); x },
  "unpack('C*')"  => ->(s) { s.unpack("C*") },
  "unpack('U*')"  => ->(s) { s.unpack("U*") },
  "unpack('a2')"  => ->(s) { s.unpack("a2") },
  "unpack1('m0')" => ->(s) { s.unpack1("m0") },
  "to_i"          => ->(s) { s.to_i },
  "to_f"          => ->(s) { s.to_f },
  "hex"           => ->(s) { s.hex },
  "to_c"          => ->(s) { s.to_c },
  "to_r"          => ->(s) { s.to_r },
  "%"             => ->(s) { "<%s>" % s },
  "% b"           => ->(s) { "<%s>".b % s },
  "format(%c)"    => ->(s) { format("%c", s) },
  "format(%-10s|)"=> ->(s) { format("%-10s|", s) },
  "sum"           => ->(s) { s.sum },
  "crypt"         => ->(s) { s.crypt("ab") },
  "String.new(enc)"=> ->(s) { String.new(s, encoding: "EUC-JP") },
  "String.new(cap)"=> ->(s) { String.new(s, capacity: 100) },
  "Symbol.all?"   => ->(s) { s.to_sym.to_proc.call(Struct.new(:x).new(1)) rescue $!.class },
  "Marshal"       => ->(s) { Marshal.load(Marshal.dump(s)) },
  "Marshal bytes" => ->(s) { Marshal.dump(s).bytes },
  "JSON"          => ->(s) { require "json"; JSON.generate([s]) },
  "JSON parse"    => ->(s) { require "json"; JSON.parse(JSON.generate([s]))[0] },
  "freeze.frozen?"=> ->(s) { s.dup.freeze.frozen? },
  "-@"            => ->(s) { -s.dup },
  "+@"            => ->(s) { x = +s.dup.freeze; x.frozen? },
  "hash stable"   => ->(s) { s.hash == s.dup.hash },
  "each_grapheme" => ->(s) { s.each_grapheme_cluster.to_a },
  "chars.join"    => ->(s) { s.chars.join },
  "chars.join==s" => ->(s) { s.chars.join == s },
  "codepoints.pack"=> ->(s) { s.codepoints.pack("U*") },
  "Integer#chr"   => ->(s) { s.getbyte(0).chr(s.encoding) },
  "Integer#chr(enc)"=> ->(s) { 0x3042.chr(s.encoding) },
  "concat multi"  => ->(s) { s.dup.concat("x", "あ") },
  "Encoding.compatible?" => ->(s) { Encoding.compatible?(s, "あ") },
  "Encoding.compatible? b" => ->(s) { Encoding.compatible?(s, "\xff".b) },
  "Encoding.compatible? ascii" => ->(s) { Encoding.compatible?(s, "abc") },
  "Encoding.compatible? empty" => ->(s) { Encoding.compatible?(s, "".encode("EUC-JP")) },
}
# bin/encoding-matrix isolates a crash: `LIST=units` / `LIST=cases` name
# the inputs / cases, `ONLY_INPUT=<input>` runs one input, and `SKIP` is
# `"<input>\t<case>|…"` for the rows that crashed the process.
case ENV["LIST"]
when "units" then puts INPUTS.keys; exit
when "cases" then puts CASES.keys; exit
end
only = ENV["ONLY_INPUT"]; skip = (ENV["SKIP"] || "").split("|")
INPUTS.each do |iname, s|
  next if only && iname != only
  CASES.each do |cname, blk|
    next if skip.include?("#{iname}\t#{cname}")
    $stdout.flush
    r = begin
      show(blk.call(s.dup))
    rescue Exception => e
      "#{e.class}: #{e.message.lines.first&.chomp}"
    end
    puts "#{iname}\t#{cname}\t#{r}"
  end
end
