[package]
name = "monoruby"
version = "0.3.0"
authors = ["monochrome <sisshiki@mac.com>"]
description = "another CRuby implementation with JIT compiler."
repository = "https://github.com/sisshiki1969/monoruby"
edition = "2021"
license = "MIT OR Apache-2.0"
default-run = "monoruby"
build = "build.rs"

[[bin]]
name = "monoruby"

[[bin]]
name = "irm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
dump-bc = []
emit-asm = ["dump-bc"]
emit-bc = ["dump-bc"]
jit-log = []
jit-debug = []
no-jit = []
deopt = ["jit-log", "dump-bc"]
gc-log = []
gc-debug = []
gc-stress = []
profile = ["dump-bc"]
perf = []
emit-cfg = ["dump-bc"]

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
rustyline = "15.0.0"
paste = "1.0.15"
monoasm_macro = { git = "https://github.com/sisshiki1969/monoasm.git", branch = "rc" }
monoasm = { git = "https://github.com/sisshiki1969/monoasm.git", branch = "rc" }
ruruby-parse = { path = "../ruruby-parse" }
monoruby-attr = { path = "../monoruby_attr" }
num = "0.4.3"
fxhash = "0.2.1"
tempfile = "3.19.1"
dtoa = "1.0.10"
chrono = "0.4.40"
smallvec = { git = "https://github.com/sisshiki1969/rust-smallvec.git", features = [
  "const_generics",
] }
escape_string = "0.1.2"
hex = "0.4.3"
rand = "0.9.0"
indexmap = "2.9.0"
regex = "1.11.1"
fancy-regex = "0.14.0"
libc = "0.2.171"
getrandom = "0.3.2"
rand_mt = { version = "5.0.0", features = ["rand-traits"] }
bitvec = "1.0.1"
ansi_term = "0.12.1"
dirs = "6.0.0"
globset = "0.4.14"
html-escape = "0.2.13"
unicode-general-category = "1.0.0"
signal-hook = "0.3.17"

[build-dependencies]
dirs = "6.0.0"
